CREATE DATABASE AWM;

CREATE USER;

CREATE TABLE USERS(
    INT ID PRIMARY KEY AUTO_INCREMENT;
    VARCHAR2(32) NAME NOT NULL,
    VARCHAR2(10) PHONE NOT NULL,
    VARCHAR2(256) EMAIL NOT NULL,
    VARCHAR2(32) PASSWORD NOT NULL
);

CREATE TABLE MECHANICS(
    INT ID PRIMARY KEY AUTO_INCREMENT,
    INT USER REFERENCES USERS(ID) NOT NULL,
    VARCHAR2(32) GARAGE_NAME NOT NULL,
    FLOAT LOC_LAT NOT NULL,
    FLOAT LOC_LON NOT NULL
);

CREATE TABLE SESSION(
    INT ID PRIMARY KEY AUTO_INCREMENT,
    INT USER REFERENCES USERS(ID) NOT NULL,
    DATETIME DATE_AND_TIME NOT NULL TIMESTAMP,
    VARCHAR2(32) TOKEN
);

CREATE TABLE BOOK(
    INT ID PRIMARY KEY AUTO_INCREMENT,
    INT USER REFERENCES USERS(ID) NOT NULL,
    INT MECHANIC REFERENCES MECHANICS(ID) NOT NULL
);